import React from 'react'
import './App.css'

const Home = () => {
    return (
        <div className="container-fluid">
             <h1 className="text-center text-success bg-light display-6 ">Student management System</h1>
            <div className="row">
                <div className="col-8">
                <img src="https://jischoolerp.com/blog/image/88/post-1573194672-image_file-user_id_2.png" alt="home_image"/>
               </div>
                <div className="col-2 display-7   bg-light ">
                    <h5 className=" text-primary">"Student Management System  is a solution tool that is designed to track, maintain and manage
                         all the data generated by a School, including the grades of a student, their attendance, their 
                         interpersonal activities records, etc.,"</h5>
                     </div>
            </div>
            
            
          
        </div>
    )
}

export default Home
